# Generated by Django 3.2 on 2021-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_applicant_details_carrer_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_details',
            name='Carrer_goals',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
