# Generated by Django 3.2 on 2021-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_applicant_details_carrer_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_details',
            name='Carrer_goals',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
