# Generated by Django 3.2 on 2021-05-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_applicant_details_carrer_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAdvisor_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Have_you_examined_the_applicant_proposed_researchplan', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=25)),
                ('Do_you_consider_the_applicant_research_plan_reasonable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25)),
                ('If_no_please_comment_1', models.CharField(blank=True, max_length=128)),
                ('Research_within_the_time_frame_indicated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=25)),
                ('If_no_please_comment_2', models.CharField(blank=True, max_length=128)),
                ('Will_the_applicant_receive_academic_credit_this_work', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=25)),
                ('If_yes_please_indicate_the_nature_of_this_academic_credit', models.CharField(blank=True, max_length=128)),
                ('Work_of_the_applicant_on_this_project', models.CharField(blank=True, max_length=256)),
                ('Applicant_receives_this_research_award', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=25)),
                ('Upload_your_reference_commitment_letter_signed', models.FileField(blank=True, max_length=256, upload_to='app/')),
                ('faculty_num', models.CharField(default='', max_length=10)),
                ('Applicant_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.applicant_details')),
            ],
        ),
    ]
