# Generated by Django 3.2 on 2021-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_applicant_details_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyadvisor_fields',
            name='Upload_your_reference_commitment_letter_signed',
            field=models.FileField(blank=True, max_length=256, upload_to='media/upload'),
        ),
    ]
