# Generated by Django 2.1.1 on 2020-08-26 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advisor1_FirstName', models.CharField(max_length=128, null=True)),
                ('Advisor1_LastName', models.CharField(default=None, max_length=30, null=True)),
                ('Advisor1_Department', models.CharField(default=None, max_length=100, null=True)),
                ('Advisor1_Inst', models.CharField(default='', max_length=128)),
                ('Advisor1_Street_Address', models.CharField(default=None, max_length=128, null=True)),
                ('Advisor1_City', models.CharField(default=None, max_length=50, null=True)),
                ('Advisor1_State', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='', max_length=50, null=True)),
                ('Advisor1_Zip_Code', models.CharField(default=None, max_length=20, null=True)),
                ('Advisor1_Telephone', models.CharField(default=None, max_length=13, null=True)),
                ('Advisor1_Fax', models.CharField(default=None, max_length=30, null=True)),
                ('Advisor1_Email', models.EmailField(default=None, max_length=128, null=True)),
                ('Advisor2_FirstName', models.CharField(blank=True, default='', max_length=128)),
                ('Advisor2_LastName', models.CharField(blank=True, default='', max_length=30)),
                ('Advisor2_Department', models.CharField(blank=True, default='', max_length=100)),
                ('Advisor2_Inst', models.CharField(blank=True, default='', max_length=128)),
                ('Advisor2_Street_Address', models.CharField(blank=True, default='', max_length=128)),
                ('Advisor2_City', models.CharField(blank=True, default='', max_length=50)),
                ('Advisor2_State', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='', max_length=50)),
                ('Advisor2_Zip_Code', models.CharField(blank=True, default='', max_length=20)),
                ('Advisor2_Telephone', models.CharField(blank=True, default='', max_length=13)),
                ('Advisor2_Fax', models.CharField(blank=True, default='', max_length=30)),
                ('Advisor2_Email', models.EmailField(blank=True, default='', max_length=128)),
                ('design_area', models.CharField(choices=[('AE', 'Airport Environmental Interactions'), ('AM', 'Airport Management and Planning'), ('AO', 'Airport Operations and Maintenance'), ('RS', 'Runway Safety/Runway Incursions/Runway Excursions')], default='', max_length=50)),
                ('Specific_Challenge', models.CharField(default='', max_length=264)),
                ('Briefly_Describe', models.CharField(default='', max_length=264)),
                ('project_team', models.CharField(choices=[('Student Team', 'Student Team'), ('Individual Student', 'Individual Student')], default='', max_length=50)),
                ('project_undertaken', models.CharField(choices=[('Design Class', 'Design Class'), ('Independent Study', 'Independent Study'), ('Student Society Chapter', 'Student Society Chapter'), ('Other', 'Other')], default='', max_length=50)),
                ('Other', models.CharField(blank=True, max_length=100)),
                ('Students_Involved', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Both', 'Both')], default='', max_length=50)),
                ('UG_level', models.CharField(blank=True, max_length=50)),
                ('no_of_participants_UG', models.PositiveIntegerField(default='0')),
                ('no_of_participants_G', models.PositiveIntegerField(default='0')),
                ('no_of_participants_FA', models.PositiveIntegerField(default='0')),
                ('no_of_participants_Other', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(default='', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inst', models.CharField(default='', max_length=128)),
                ('title', models.CharField(default='', max_length=200)),
                ('design_area', models.CharField(choices=[('AE', 'Airport Environmental Interactions'), ('AM', 'Airport Management and Planning'), ('AO', 'Airport Operations and Maintenance'), ('RS', 'Runway Safety/Runway Incursions/Runway Excursions')], max_length=3)),
                ('Specific_Challenge', models.CharField(default='', max_length=264)),
                ('Students_Involved', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Both', 'Both')], default='', max_length=20)),
                ('Advisor1_FirstName', models.CharField(max_length=128, null=True)),
                ('Advisor1_LastName', models.CharField(default=None, max_length=30, null=True)),
                ('Advisor1_Department', models.CharField(default=None, max_length=100, null=True)),
                ('Advisor1_Street_Address', models.CharField(default=None, max_length=128, null=True)),
                ('Advisor1_City', models.CharField(default=None, max_length=50, null=True)),
                ('Advisor1_State', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='', max_length=50, null=True)),
                ('Advisor1_Zip_Code', models.CharField(default=None, max_length=20, null=True)),
                ('Advisor1_Telephone', models.CharField(default=None, max_length=13, null=True)),
                ('Advisor1_Fax', models.CharField(default=None, max_length=30, null=True)),
                ('Advisor1_Email', models.EmailField(default=None, max_length=128, null=True)),
                ('Advisor2_FirstName', models.CharField(blank=True, default='', max_length=128)),
                ('Advisor2_LastName', models.CharField(blank=True, default='', max_length=30)),
                ('Advisor2_Department', models.CharField(blank=True, default='', max_length=100)),
                ('Advisor2_Street_Address', models.CharField(blank=True, default='', max_length=128)),
                ('Advisor2_City', models.CharField(blank=True, default='', max_length=50)),
                ('Advisor2_State', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='', max_length=50)),
                ('Advisor2_Zip_Code', models.CharField(blank=True, default='', max_length=20)),
                ('Advisor2_Telephone', models.CharField(blank=True, default='', max_length=13)),
                ('Advisor2_Fax', models.CharField(blank=True, default='', max_length=30)),
                ('Advisor2_Email', models.EmailField(blank=True, default='', max_length=128)),
                ('num_team_members', models.PositiveIntegerField(default='0')),
                ('Other_Participants', models.CharField(blank=True, default='', max_length=100)),
                ('Describe', models.CharField(blank=True, default='', max_length=256)),
                ('ACRP_University', models.CharField(max_length=256, null=True)),
                ('Other', models.CharField(blank=True, default='', max_length=100)),
                ('Upload', models.FileField(max_length=256, null=True, upload_to='upload')),
                ('stat', models.CharField(choices=[('Approved', 'Application Approved'), ('Rejected', 'Application Rejected'), ('Evaluation Saved', 'Save for later submission'), ('Evaluation Completed', 'Final submission')], default='Application is submitted', max_length=25)),
                ('reason', models.CharField(default='', max_length=128)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_title', models.CharField(max_length=500)),
                ('Q_questions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='responce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_score', models.FloatField(blank=True, default='0.5', max_length=100)),
                ('Q_comments', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acrpapp.emp')),
                ('design_app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acrpapp.DesignApp')),
                ('evalutor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=20)),
                ('design_app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acrpapp.DesignApp')),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('Evaluation Saved', 'Save for later submission'), ('Evaluation Completed', 'Final submission')], max_length=25)),
                ('design_app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acrpapp.DesignApp')),
                ('evalutor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignApp1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('acrpapp.designapp',),
        ),
        migrations.CreateModel(
            name='DesignApp2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('acrpapp.designapp',),
        ),
        migrations.CreateModel(
            name='DesignApp3',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('acrpapp.designapp',),
        ),
    ]
