# Generated by Django 2.1.1 on 2020-09-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrpapp', '0003_auto_20200911_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designapp',
            name='Upload',
            field=models.FileField(max_length=256, null=True, upload_to='media'),
        ),
    ]
