# Generated by Django 3.2 on 2021-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrpapp', '0005_auto_20200929_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designapp',
            name='ACRP_University',
            field=models.CharField(max_length=256, null=True, verbose_name='Please check How did you hear about the ACRP University Design Competition for Addressing Airport Needs?'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
