# Generated by Django 3.2 on 2021-04-27 19:39

import acrpapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrpapp', '0006_auto_20210427_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designapp',
            name='Upload',
            field=models.FileField(max_length=256, null=True, upload_to='media/', validators=[acrpapp.validators.validate_file_size]),
        ),
    ]
