# Generated by Django 3.2 on 2021-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrpapp', '0009_alter_designapp_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responce',
            name='Q_comments',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
