# Generated by Django 3.2 on 2021-09-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrpapp', '0010_alter_responce_q_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='design_area',
            field=models.CharField(choices=[('AE', 'Airport Environmental Interactions'), ('AM', 'Airport Management and Planning'), ('AO', 'Airport Operations and Maintenance'), ('RS', 'Runway Safety/Runway Incursions/Runway Excursions Including Aprons,Ramps,and Taxiways')], default='', max_length=50),
        ),
    ]
